apiVersion: apps.my.domain/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: chatgpt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: chatgpt
  name: app-sample
spec:
  # TODO(user): Add fields here
