# File: .github/workflows/test.yml

name: Run Azure AKS CRD Install For APP
on:
  push:
    branches:
      - stoof
      - main

permissions:
      id-token: write
      contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd

    #   - name: 'Install aks CLI'
    #     run: |
    #       az aks install-cli

      - name: 'Make Build'
        run: |
            make build

      - name: 'Make Manifest'
        run: |
            make manifests

      - name: 'Grab AKS Credentials'
        run: |
          az aks get-credentials --resource-group doks --name doks

      - name: 'Where am I?'
        run: |
          ls ./bin

      - name: 'Create Yaml File'
        run: |
          ../bin/kustomize build ./config/default > stoof.yaml

      - name: 'Apply Yaml File'
        run: |
          kubectl apply -f stoof.yaml