# File: .github/workflows/test.yml

name: Run Azure AKS CRD Install For APP
on:
  push:
    branches:
      - stoof
      - main

permissions:
      id-token: write
      contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Make Build'
        run: |
            make build

    #   - name: 'Make Manifest'
    #     run: |
    #         make manifests

      - name: 'Make docker-build'
        run: |
          make docker-buildx

    #   - name: 'Make docker-push'
    #     run: |
    #       make docker-push

      - name: 'Grab AKS Credentials'
        run: |
          az aks get-credentials --resource-group doks --name doks-2

      - name: 'Make Un Deploy'
        run: |
          make undeploy

      - name: 'Make Deploy'
        run: |
          make deploy